# Getting Started with pandas

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

## Introduction to pandas Data Structures

### Series

In [2]:
#시리즈는 일련의 객체를 담을 수 있는 1차원 배열 형태를 띄고 있는 자료구조이다. [열]과 같은 개념이다.
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [68]:
type(obj) #obj는 판다스의 시리즈 타입임을 알 수 있다.

pandas.core.series.Series

In [3]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [4]:
obj.index #index는 0:4 즉 0,1,2,3까지이다.

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2 #index를 지정해서 바꿀 수도 있다.

d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [8]:
obj2['a'] #인덱스로 저장된 값을 불러울 수도 있고

-5

In [10]:
obj2['d'] = 6 #값을 대입할 수도 있다.

In [11]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [12]:
obj2 #대입된 값은 원본에 관여한다.

d    6
b    7
a   -5
c    3
dtype: int64

In [13]:
obj2[obj2 > 0]  #값에 대한 연산을 수행할 수도 있다. 그래도 index와 값은 맞아 떨어진다.

d    6
b    7
c    3
dtype: int64

In [14]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [15]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [16]:
'b' in obj2 #인덱스에 대한 연산을 수행할 수도 있다.

True

In [17]:
'e' in obj2

False

In [19]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [20]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4 #사전의 키값에 맞춰서 들어가기 때문에 지정되지 않은 'California' 인덱스는 값을 받지 못해 NaN(Not a Number) 처리 된다.
#NaN은 Null과 같은 값이다.

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [21]:
pd.isnull(obj4) #isnull을 통해 NaN에 속하는 값을 찾을 수도 있고

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [22]:
pd.notnull(obj4) #notnull 또한 찾을 수 있다. 둘의 차이는 조건으로, null이 맞느냐, 아니냐 물음의 차이이다.

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [23]:
obj4.isnull() #이를 통해 obj4에 NaN값이 있니? 물어봤을 때 California 인덱스는 '응'이라고 자랑스럽게 외쳐준다.

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [24]:
obj3

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [26]:

obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [25]:

obj3 + obj4 #색인된 데이터의 산술연산이 가능하다. Utah의 경우, obj3에 값이 있음에도 obj4에 없어서 누락된다.

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [27]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [28]:
obj4.name = 'population' #obj4 시리즈의 '속성'인 '시리즈명'을 변경할 수 있다. 여기서는 'population'으로 변경했다.
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [29]:
obj4.index.name = 'state' #obj4 시리즈의 '속성'인 '인덱스명' 또한 변경할 수 있다.
#California라는 인덱스 위에 state라는 속성이 들어가있다.
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

0    4
1    7
2   -5
3    3
dtype: int64

In [31]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj #obj의 index 자리를 위와같이 대체한다.

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame

In [35]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]} 
frame = pd.DataFrame(data) #데이터프레임은 시리즈의 집합체이다. 일종의 표를 생각하면 된다. 
#흔히 말하는 엑셀처럼 행은 1,2,3,4같은 인덱스가 있고 열 또한 고유의 헤더가 존재한다.
#각 열(Column)은 서로 다른 값을 가질 수 있다.

In [37]:
data #여기서는 dict 형식으로 3개의 키:값을 생성했다. 

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [40]:
frame #이를 dataframe으로 옮기면 아래와 같이 나온다. 각 dict에 있던 키:값이 하나의 열이 된다.

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [70]:
type(frame) #frame은 판다스의 DataFrame 타입임을 알 수 있다.

pandas.core.frame.DataFrame

In [41]:
frame.head() #어째선지 마지막줄이 사라졌다.

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [43]:
frame.head(3) #head는 기준이 되는 데이터프레임에서 가장 상단에 있는 값을 순차적으로 뽑아준다.

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7
2  Ohio  2002  3.6

In [42]:
frame.tail() #어째선지 0번째 인덱스 첫줄이 사라졌다.

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [44]:
frame.tail(3) #tail은 기준이 되는 데이터프레임에서 가장 하단에 있는 값을 순차적으로 뽑아준다.

state  year  pop
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [45]:
pd.DataFrame(data, columns=['year', 'state', 'pop']) #열의 속성(header)를 변경할 수도 있다.

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [47]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four','five', 'six'])
frame2 #열의 속성 변경은 당연한거고, 만약 새로운 열이 필요하면 추가하면 그대로 들어가진다. 다만 값은 NaN. 
#행 index를 지정해서 바꿀 수도 있다.

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [48]:
frame2.columns #추가가 잘 되었다.

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [49]:
frame2['state'] #열 하나만 지정해서 뽑을 수도 있다.

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [50]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [51]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [52]:
frame2.loc['three'] #loc는 location이다. 행인덱스 'three'에 속하는 각 열 값을 뽑아준다.

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [53]:
frame2['debt'] = 16.5 #열을 지정해서 값을 지정할 수도 있다.
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [55]:
frame2['debt'] = np.arange(6.) #numpy의 arange를 활용해 0부터 6.0 이전까지, 증가값 1로 올라가게 할 수도 있다)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [61]:
frame2['debt'] = np.arange(1,6) #열의 값이 일치하지 않다면 오류가 발생한다.
frame2

ValueError: Length of values does not match length of index

In [63]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [64]:
frame2['debt'] = val #다른 시리즈를 행인덱스 지정까지 해서 넣을 수도 있다.
frame2 #val은 two에 -1.2, four에 -1.5, five에 -1.7이 대입된걸 확인할 수 있다.

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [65]:
frame2['eastern'] = frame2.state == 'Ohio' #eastern이라는 열을 추가할건데, 거기에 state가 Ohio인지에 대한 여부를 저장할 수 있다.
frame2 #이런 논리연산도 가능하다.

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [66]:
del frame2['eastern']
frame2.columns #del을 통해 eastern을 삭제하고 열을 출력하니 삭제된 거 빼고 다 나온다.

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [67]:
frame2 #원본에 영향을 미치는 것 또한 확인할 수 있다.

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [72]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
pop  #pop이라는 dict 생성

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [74]:
type(pop)

dict

In [75]:
frame3 = pd.DataFrame(pop)
frame3 #pop dict를 이용해 데이터프레임을 생성한다.

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [76]:
type(frame3)

pandas.core.frame.DataFrame

In [79]:
type(frame3['Nevada']) #Nevada가 시리즈면 Ohio는 당연히 시리즈일 것이다.

pandas.core.series.Series

In [85]:
frame3.T #numpy때처럼 T를 통해 행과 열을 뒤집을 수 있다.

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [81]:
frame3 #실제 데이터에는 영향을 주지 않는다.

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [86]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [88]:
pd.DataFrame(pop)#, index=[2000, 2001, 2002]) 

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [89]:
pd

<module 'pandas' from 'C:\\Users\\Playdata\\Anaconda3\\lib\\site-packages\\pandas\\__init__.py'>

In [91]:
!pip show pandas #pandas가 잘 설치되었는지 주피터 노트북에서도 확인 가능.

Name: pandas
Version: 0.23.4
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: http://pandas.pydata.org
Author: None
Author-email: None
License: BSD
Location: c:\users\playdata\anaconda3\lib\site-packages
Requires: python-dateutil, pytz, numpy
Required-by: seaborn, odo


In [93]:
# p167 교재와 다름, 
pd.DataFrame(pop, index=pd.Int64Index([2001, 2000, 2002])) #인덱스 지정을 통해 순서관계를 정할 수도 있다.

Nevada  Ohio
2001     2.4   1.7
2000     NaN   1.5
2002     2.9   3.6

In [94]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [103]:
frame3['Ohio'][:-1] #데이터 색인이 가능하다. ['Ohio']열에 속하는 데이터 중 [:-1]을 하면 마지막 행의 갯수 -1을 한 값을 출력해준다. 

2000    1.5
2001    1.7
Name: Ohio, dtype: float64

In [104]:
frame3['Ohio']

2000    1.5
2001    1.7
2002    3.6
Name: Ohio, dtype: float64

In [105]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]} #pdata를 통해 frame3에 있는 Ohio중 마지막 행 -1만큼, Nevada중 0,1 행만큼 구해준다.
#둘의 데이터수는 같다.
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [107]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [108]:
frame3.index.name = 'year' 
frame3.columns.name = 'state'
frame3 #frmae 3의 인덱스명도 바꾸고 싶고 열이름도 바꾸고 싶다. 그래서 지정해서 바꾸니 뭔가 붕 떠버렸다.

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [109]:
frame3.values #frame3의 값들. 속성명(인덱스명/열이름)은 반영되지 않았음을 확인할 수 있다.

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [112]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [111]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### Index Objects

In [113]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
obj #인덱스 이름은 a,b,c로 범위를 3 이전까지 지정해서 시리즈 만든다.

a    0
b    1
c    2
dtype: int64

In [114]:
index = obj.index
index #obj의 인덱스(행)

Index(['a', 'b', 'c'], dtype='object')

In [115]:
index[1:] #인덱스값 기준으로 하면 1부터 시작이니 1부터 2까지만 나온다.

Index(['b', 'c'], dtype='object')

index[1] = 'd'  # TypeError

In [116]:
labels = pd.Index(np.arange(3))
labels #labels에 numpy arange로 3 이전까지 생성

Int64Index([0, 1, 2], dtype='int64')

In [118]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2 #만들어진 인덱스를 다른 시리즈를 만들 때 참조시킬 수 있다.

0    1.5
1   -2.5
2    0.0
dtype: float64

In [120]:
obj2.index #이 때 obj2 인덱스는 당연히 labels와 동일하다.

Int64Index([0, 1, 2], dtype='int64')

In [122]:
obj2.index is labels #그래서 인덱스 안에 labels가 있는 것도 참이라 나온다.

True

In [123]:
frame3 #인덱스가 아까 붕떠버린 frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [124]:
frame3.columns #frame3의 열은 두개이다. 

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [125]:
'Ohio' in frame3.columns #Ohio가 frame3 열 안에 있다.

True

In [126]:
2003 in frame3.index #2003은 frame3 행 안에 없다.

False

In [127]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels #인덱스명을 중복해서도 만들 수 있다.

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## Essential Functionality

### Reindexing

In [128]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj 

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [129]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2 #reindex 인덱스재설정을 할 수 있다. 인덱스의 순서가 바뀌면 당연히 안에 들어 있던 값도 따라 움직인다.

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [130]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3 

0      blue
2    purple
4    yellow
dtype: object

In [131]:
obj3.reindex(range(6), method='ffill') #ffill 메소드를 사용하면 누락된 값을 그대로 채워넣을 수 있다.
#3행의 range를 6(0~5)까지 늘리고 method를 사용 했을 때 지정된 인덱스값 사이에 가장 첫값을 따라간다.
#좀 더 쉽게 말하면 0에는 blue, 2에는 purple, 4에는 yellow가 들어있는데,
#1은 0과 1 사이에 있지만 오름차순기준 0이 더 첫값이니 0의 인덱스값을 따라가 blue가 된다.

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [132]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])

In [133]:
frame #arange를 통해 0부터 8까지 만들고 3x3의 2차원 배열로 만들고 이를 그대로 dataframe화 시켰다.

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [135]:
type(frame['Ohio']) #당연히 시리즈다

pandas.core.series.Series

In [137]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2 #인덱싱재설정을 통해 행을 추가할 수 있다.

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [139]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states) #열도 재설정을 통해 인덱싱재설정을 할 수 있다. 

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### Dropping Entries from an Axis

In [140]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj 

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [141]:
new_obj = obj.drop('c')
new_obj #인덱스를 지정해서 '지워버릴' 수도 있다. 'c' 행덱스가 삭제된 모습

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [143]:
obj.drop(['d', 'c']) #대괄호를 지정해서 여러개의 행 삭제도 가능하다. d,c가 삭제된 모습

a    0.0
b    1.0
e    4.0
dtype: float64

In [144]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [145]:
data.drop(['Colorado', 'Ohio']) 

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [146]:
data #삭제해도 실제 데이터에 영향을 미치지 않는다.

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [151]:
data.drop('two', axis=1) #axis=1은 열 삭제이다.

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [152]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [153]:
data.drop(['two', 'four'], axis='columns') #axis=1이 열이니 columns도 axis=1이나 마찬가지다.

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [157]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [156]:
obj.drop('c', inplace=True)
obj #inplace 기능을 사용하면 내 장소 안에서 처리를 할지에 대한 여부를 물어보는데, 
#True를 하면 따로 복사본을 만들지 않고 내 집에서 처리한다.
#그리고 내 집에서 삭제된 상태로 한번 더 실행하면 해당 인덱스가 당연히 없기 때문에 오류가 발생한다.

KeyError: "['c'] not found in axis"

### Indexing, Selection, and Filtering

In [171]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [172]:
obj['b'] #인덱스명을 지정하건, 인덱스고유값을 지정하건 잘 나온다.

1.0

In [173]:
obj[1]

1.0

In [174]:
obj[2:4] #슬라이스 가능

c    2.0
d    3.0
dtype: float64

In [175]:
obj[['b', 'a', 'd']] #아무튼 가능

b    1.0
a    0.0
d    3.0
dtype: float64

In [176]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [177]:
obj[obj < 2] #값 연산도 가능

a    0.0
b    1.0
dtype: float64

In [178]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [179]:
obj['b':'c'] #인덱스고유값 슬라이싱과 달리 인덱스명으로 슬라이싱하면 종료값까지 뽑아내준다.
#고유값이었으면 [1:3]이어야 동일한 값이 나올텐데... 헷갈리지 않게 주의하자.

b    1.0
c    2.0
dtype: float64

In [180]:
obj[1:3]

b    1.0
c    2.0
dtype: float64

In [181]:
obj['b':'c'] = 5 #값 대입 가능
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [182]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [184]:
data['two'] #two 열에 해당하는 행인덱스

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [189]:
data[['three', 'one']] #뭐가 먼저 나올지 정할 수도 있는데, 대괄호 두개를 묶어서 설정하자.

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [190]:
data[:2] #행 인덱스를 0,1만 뽑아준다.

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [191]:
data 

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [192]:
data[data['three'] > 5] #연산도 가능하다.

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [193]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [195]:
data[data < 5] = 0 

In [196]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### Selection with loc and iloc

In [197]:
data 

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [199]:
data.loc['Colorado', ['two', 'three']] #loc를 통해 Colorado 행에서 two와 three 열을 선택한다.

two      5
three    6
Name: Colorado, dtype: int32

In [200]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [202]:
data.iloc[2] #iloc는 인덱스로케이션으로 행이름,열이름이 아닌 인덱스고유값으로 지정이 가능하다. [2]는 3번째 행 즉 Utah임

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [203]:
data.iloc[2, [3, 0, 1]] #iloc를 통해 Utah 행에서 4번째 열, 1번째 열, 2번째 열로 뽑아준다. 각각 four, one, two다.

four    11
one      8
two      9
Name: Utah, dtype: int32

In [204]:
data.iloc[[1, 2], [3, 0, 1]] #iloc를 통해 여러개 뽑기가 가능하다. 어쨌든 항상 행이 먼저다.

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [205]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [206]:
data.loc[:'Utah', 'two'] #loc도 iloc처럼 활용할 수 있다. :Utah는 종료가 Utah라는 거고, 아까 적었듯 이름 인덱싱은 지정된 곳까지 뽑는다.
#그래서 [[0,1,2], [1]] 과 같은 값을 가진다. [[:3], [1]]이 기도 하다.

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [207]:
data.iloc[:, :3][data.three > 5] #iloc를 통해 모든 행을 뽑아주고 거기서 0,1,2 열만 뽑는데 three 열의 값이 5보다 커야 한다.
#그래서 Ohio three는 5보다 작기 때문에 나오지 못했다.

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [208]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### Integer Indexes

ser = pd.Series(np.arange(3.))
ser
ser[-1]

In [209]:
ser = pd.Series(np.arange(3.))

In [210]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [218]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [219]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [220]:
ser2[-1] #시작값이 -1즉 마지막값만 뽑는다.

2.0

In [221]:
ser[:1] #인덱스 슬라이싱시 종료값 :1 즉 0까지만 뽑는다.

0    0.0
dtype: float64

In [222]:
ser.loc[:1] #loc를 통해 0과 1까지의 행이름에 속하는 값을 뽑아준다.

0    0.0
1    1.0
dtype: float64

In [223]:
ser.iloc[:1] #iloc는 가차없다. :1이면 0만 해당된다.

0    0.0
dtype: float64

### Arithmetic and Data Alignment

In [225]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [226]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [227]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [228]:
s1 + s2 #위와 마찬가지로 한쪽 시리즈에 있는 인덱스를 다른 곳에서 확인할 수 없으면 값은 누락되어 NaN이 된다.

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [229]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'), 
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [230]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [231]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [232]:
df1 + df2 #이는 데이터프레임 상태에서도 마찬가지이다.

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [233]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

In [234]:
df1

A
0  1
1  2

In [235]:
df2

B
0  3
1  4

In [236]:
df1-df2 #행 인덱스는 일치하지만 열은 일치하지 않아 역시 누락된다.

A   B
0 NaN NaN
1 NaN NaN

#### Arithmetic methods with fill values

In [237]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))

In [238]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [239]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [243]:
df2.loc[1, 'b'] = np.nan #1행 'b'열을 nan처리한다.

In [244]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [245]:
df1 + df2 #df1은 3행 e열 모두 없으니 3행과 e열은 몽땅 NaN이 된다.
#또한 df2에서 지정했던 1행 b열의 NaN값으로 인해 df1은 값이 있음에도 누락된다.

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [247]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [249]:
df2 #원본에는 영향없다.

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [251]:
df1.add(df2, fill_value=0) #add를 사용해 df1과 df2를 더할 때, fill_value 메소드를 사용해 NaN값을 0으로 바꿔준다. 
#기존 df1과 df2를 확인한 결과 잘 나왔음을 확인할 수 있었다.

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [252]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [253]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [254]:
1 / df1 #1 나누기 df1을 하면 각 값들에 1/n이 붙는다고 보면 된다.
#1을 0으로 나누니 inf(무한)이 되버리고 나머지는 분수가 된다.

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [256]:
df1.rdiv(1) #rdiv가 위와 같은 기능을 수행함을 확인할 수 있다.

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [257]:
df1.reindex(columns=df2.columns, fill_value=0) #df1을 인덱스 재설정을 통해 df2의 열을 가져오고, 누락될 수 있는 값을 0으로 채웠다.

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

#### Operations between DataFrame and Series

In [258]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [259]:
arr[0] #첫번째 행에 속하는거

array([0., 1., 2., 3.])

In [260]:
arr - arr[0] #모든 배열에 arr[0]에 속하는 것을 뺀다. 마치 arr[0]을 지워버릴거 같지만 사실 arr[0]을 브로드캐스팅해서 계산해버린다.
#[0 1 2 3]        [0 1 2 3]
#[4 5 6 7]    -   [0 1 2 3]
#[8 9 10 11]      [0 1 2 3]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [261]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [267]:
type(frame)

pandas.core.frame.DataFrame

In [263]:
series = frame.iloc[0]


In [268]:
type(series)

pandas.core.series.Series

In [264]:
series #시리즈에 행 인덱스고유값 0을 담았다. 즉 Utah만 넣음


b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [269]:
frame - series #위의 행렬처럼 데이터프레임과 시리즈를 빼도 마찬가지의 결과가 나온다. 브로드캐스팅처리해버린다.
#[0, 1, 2]       [0,1,2]     [0, 0, 0]
#[3, 4, 5]   -   [0,1,2]  =  [3, 3, 3]
#[6, 7, 8]       [0,1,2]     [6, 6, 6]
#[9, 10, 11]     [0,1,2]     [9, 9, 9]

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [270]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [271]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [272]:
series2 #이번엔 다른 열인덱스를 가지고 있는 시리즈를 사용한다.

b    0
e    1
f    2
dtype: int64

In [273]:
frame + series2  #서로 더하면, 인덱스 인식이 안돼서 같은 인덱스끼리 더해진거 빼고는 누락된다.

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [274]:
series3 = frame['d'] 

In [275]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [278]:
type(series3)

pandas.core.series.Series

In [276]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [286]:
frame.sub(series3, axis=1)

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

In [279]:
frame.sub(series3, axis='index') #이번에는 frame의 서브스트링을 사용해 series3에 대입할건데 axis는 index 즉 행을 기준으로 한다.
#행은 곧 0과 같다. 만약 index 기준이 아닌 열 기준으로 해버리면
#series3에 담겨진 값의 인덱스가 '행이름'이기 떄문에 행이름과 열이름이 서로 안맞아 모든 값이 누락되는 사태를 초래한다. 

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [ ]:
frame.sub(series3, axis=0)

### Function Application and Mapping

In [287]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame 

b         d         e
Utah    0.438199 -0.574104 -0.144482
Ohio   -1.338699 -0.142585  0.247101
Texas  -2.094006 -0.470874 -0.165957
Oregon  0.247256 -1.028773 -0.529844

In [288]:
np.abs(frame) #abs는 절대값으로 만들어준다.

b         d         e
Utah    0.438199  0.574104  0.144482
Ohio    1.338699  0.142585  0.247101
Texas   2.094006  0.470874  0.165957
Oregon  0.247256  1.028773  0.529844

In [290]:
f = lambda x: x.max() - x.min() #lamdba를 활용해 x는 x의 최대값과 x의 최소값을 빼는 함수가 된다.
frame.apply(f)  #apply를 통해 각 열을 하나씩 보면서 함수 계산을 해준다.

b    2.532205
d    0.886188
e    0.776946
dtype: float64

In [293]:
frame.apply(f, axis='columns') #axis를 1로 잡았을 때는 →로 계산한다.

Utah      1.012303
Ohio      1.585800
Texas     1.928050
Oregon    1.276029
dtype: float64

In [294]:
frame.apply(f, axis=1)

Utah      1.012303
Ohio      1.585800
Texas     1.928050
Oregon    1.276029
dtype: float64

In [295]:
frame

b         d         e
Utah    0.438199 -0.574104 -0.144482
Ohio   -1.338699 -0.142585  0.247101
Texas  -2.094006 -0.470874 -0.165957
Oregon  0.247256 -1.028773 -0.529844

In [297]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f) #lamdba도 되니 당연히 def 함수지정을 통해서도 가능하다. 여기서는 행이름에 'max'와 'min'도 지정해주었다.

b         d         e
min -2.094006 -1.028773 -0.529844
max  0.438199 -0.142585  0.247101

In [298]:
format = lambda x: '%.2f' % x
frame.applymap(format) #이번에는 람다 함수를 통해 x를 %.2f 포맷팅하고 x를 나눈 나머지를 구하고자 한다.
#applymap은 시리즈가 각 원소에 적용할 함수를 지정하기 위한 map메소드를 가지고 있기 때문에 붙은 이름이다.

b      d      e
Utah     0.44  -0.57  -0.14
Ohio    -1.34  -0.14   0.25
Texas   -2.09  -0.47  -0.17
Oregon   0.25  -1.03  -0.53

In [300]:
frame['e'].map(format) #이를 통해 시리즈는 map메소드를 가지고 있음을 확인할 수 있다.

Utah      -0.14
Ohio       0.25
Texas     -0.17
Oregon    -0.53
Name: e, dtype: object

### Sorting and Ranking

In [301]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [302]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [305]:
obj.sort_index() #인덱스 정렬을 통해 값을 바꿔보자. 정렬은 보통 오름차순 기준 숫자-특수문자-소문자-대문자 순으로 이루어지는데
#인덱스가 소문자이고 a,b,c,d이므로 a부터 d까지 재정렬된걸 볼 수 있다.

a    1
b    2
c    3
d    0
dtype: int64

In [307]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])

In [308]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [309]:
frame.sort_index() #행 이름을 바꾸어 three와 one이 바뀌었다. 인덱스 안에 있던 값도 따라간다.

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [310]:
frame.sort_index(axis=1) #axis=1 즉 열 기준으로 바꾸면 이렇게 된다. 열은 a,b,c,d이기 떄문

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [311]:
frame #원본변화없다

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [312]:
frame.sort_index(axis=1, ascending=False) #이번에는 열 기준 내림차순으로 정렬한 것이다.

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [314]:
obj = pd.Series([4, 7, -3, 2])

In [315]:
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [316]:
type(obj)

pandas.core.series.Series

In [317]:
obj.sort_values() #이번에는 인덱스가 아닌 값을 기준으로 오름차순 정렬했다.

2   -3
3    2
0    4
1    7
dtype: int64

In [329]:
obj = pd.Series([4, np.nan, 7, np.nan, 3, 4])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4    3.0
5    4.0
dtype: float64

In [330]:
obj.sort_values() #nan은 문자열이 아니라 정렬은 되지만 의미있는 값이 아니라서 값중 제일 마지막으로 표시된다.

4    3.0
0    4.0
5    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [331]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [332]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [334]:
frame.sort_values(by='b') #이번에는 특정 인덱스를 통해 정렬하는 방법이다. 'b' 기준 정렬을 수행한다. 

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [336]:
v=frame.sort_values(by=['a'])

In [337]:
v

b  a
0  4  0
2 -3  0
1  7  1
3  2  1

In [338]:
v.sort_values(by=['b'])

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [335]:
frame.sort_values(by=['a', 'b'])  #a와 b를 같이 정렬하는 방법이다. 
#먼저 a에 해당되는 값이 동일할 때 가장 0에 가까운 인덱스가 처음으로 출력된다.
#이 때, b 또한 값에 따라 정렬하기 떄문에 먼저 a의 값이 0인 것 중 b의 오름차순이 이뤄지고, 다시 a의 값이 1인 것중 b의 오름차순이 이뤄진다.

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [340]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [342]:
obj.rank() #순위 메소드가 존재한다. 1부터 배열의 유효한 데이터 개수까지의 순위를 매긴다고 한다.

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [343]:
obj.rank(method='first') #나타나는 순서에 따라 순위를 매길 수도 있다.

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [345]:
obj.rank(ascending=False, method='max') #오름차순 X, method의 기준은 최대값

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [346]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [349]:
frame.rank(axis=1) #열 기준으로 순위를 매길 때 → 로 처리하되 각 값의 랭킹을 지정한다.

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [350]:
frame.rank('columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### Axis Indexes with Duplicate Labels

In [351]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
#obj = pd.Series(range(3), index=['a', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [353]:
obj.index.is_unique #인덱스에 중복색인이 없는지 확인하는 것이다. unique.

False

In [354]:
obj['a'] #인덱스 a가 2개임

a    0
a    1
dtype: int64

In [355]:
obj['c']

4

In [356]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0         1         2
a  0.397287  0.866152  0.495689
a -0.804385  0.524616 -0.171689
b  1.016730  0.361131 -1.417348
b  0.418466  0.905216  0.241917

In [357]:
df.loc['b'] #b도 두개다
#색인값은 반드시 unique할 필요는 없지만 데이터 혼란 방지를 위해서 유니크처리를 해주는게 좋을 것으로 보인다.

0         1         2
b  1.016730  0.361131 -1.417348
b  0.418466  0.905216  0.241917

## Summarizing and Computing Descriptive Statistics

In [359]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [360]:
df.sum() #axis=0 기준으로 더해줌

one    9.25
two   -5.80
dtype: float64

In [361]:
df.sum(axis='columns') #axis=1 기준으로 더해줌

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [362]:
df.mean(axis='columns', skipna=False) #이때 NaN 스킵하기를 False처리하면 NaN이 그대로 반영된다. NaN이 있으면 당연히 값이 누락된다.

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [363]:
df.mean(axis='columns', skipna=True) #NaN 스킵을 통해 두 열 중 한 곳에 값이 있으면 숫자 처리가 된다. 둘 다 NaN이면... NaN이다.

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [364]:
df.idxmax() #색인의 위치를 반환하는데, 그 조건이 max인 경우이다. one은 7.10으로 가장 높은 b가, two는 -1.3으로 가장 높은 d가 나옴

one    b
two    d
dtype: object

In [365]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [366]:
df.cumsum() #열 기준 누적합을 통해 one=[1.40,1.40+7.10,NaN, 1.40+7.10+0.75] 등이 나오는 것을 본다.

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [367]:
df.describe() #describe를 사용하면 열 기준으로 된 다양한 적용함수를 확인할 수 있다.

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [368]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj #벡터에 스칼라를 곱하면... 스칼라가 브로드캐스팅이 돼서 그만큼의 벡터가 늘어난다...는 수학적인 표현이 있고
#a,a,b,c 배열에서 4를 곱해봐야 a,a,b,c만 4번 반복이 되는 기현상이 될 뿐이다.

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [370]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### Unique Values, Value Counts, and Membership

In [371]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [372]:
uniques = obj.unique()
uniques #중복되는 인덱스를 unique하게 만들어준다.

array(['c', 'a', 'd', 'b'], dtype=object)

In [374]:
obj.value_counts() #값의 갯수를 셀 수 있다.

c    3
a    3
b    2
d    1
dtype: int64

In [375]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [377]:
mask = obj.isin(['b', 'c'])
mask #obj 안에 'b'와 'c'가 들어있는지 체크

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [380]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [381]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [382]:
to_match 

0    c
1    a
2    b
3    b
4    c
5    a
dtype: object

In [384]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [386]:
unique_vals

0    c
1    b
2    a
dtype: object

In [387]:
pd.Index(unique_vals).get_indexer(to_match) #이번에는 unique_vals에 to_match의 인덱스를 얻는다.
#그래서 0,1,2,3,4,5 여야되는데 아래처럼 나온다

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [388]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [390]:
result = data.apply(pd.value_counts).fillna(0)
result #fillna를 통해 NaN과 같은 값을 안에 있는 값으로 처리할 수도 있다. 여기서는 0으로 처리.

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

## 누락된 데이터 처리하기

1. 누락된 데이터를 처리하는 일은 데이터 분석 애플리케이션에서 빈번한 작업
- 모든 기술 통계는 누락된 데이터를 배제하고 처리
- 처리 방법 1 : 수집된 데이터를 직접 제거
- 처리 방법 2 : dropna 함수 사용하여 처리 

In [391]:
from numpy import nan as NA

Series의 NA값 제거해 보기

In [392]:
data = Series([1, NA, 3.5, NA, 7])

In [393]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [394]:
data.dropna() #dropna를 사용해 NaN값을 제거할 수 있다.

0    1.0
2    3.5
4    7.0
dtype: float64

In [395]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [397]:
data[data.notnull()] #notnull로도 위와 같은 데이터를 뽑을 수 있다.

0    1.0
2    3.5
4    7.0
dtype: float64

DataFrame의 NA값 제거하기

In [399]:
data = DataFrame([[1., 6.5, 3.], [1., NA, NA], [NA, NA, NA], [NA, 6.5, 3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [400]:
cleaned = data.dropna()
cleaned 

0    1    2
0  1.0  6.5  3.0

In [401]:
data 

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [403]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [404]:
data #drop은 원본을 반영하지 않기 때문에 원본을 반영하고 싶으면 inplace를 쓰면 됨

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [405]:
data[4] = NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [406]:
df = DataFrame(np.random.randn(7, 3))

In [407]:
df

0         1         2
0 -1.676363 -0.280028 -0.843334
1  0.560776 -0.195217  0.746081
2  0.674205 -2.527892 -0.628193
3 -0.172477  1.196858  0.759635
4  1.394465 -1.217235  1.430571
5 -0.154991 -0.303014 -1.451250
6  0.991851 -0.085244  0.632400

In [408]:
df.loc[:4, 1] = NA

In [409]:
df

0         1         2
0 -1.676363       NaN -0.843334
1  0.560776       NaN  0.746081
2  0.674205       NaN -0.628193
3 -0.172477       NaN  0.759635
4  1.394465       NaN  1.430571
5 -0.154991 -0.303014 -1.451250
6  0.991851 -0.085244  0.632400

In [410]:
df.loc[:2, 2] = NA
df

0         1         2
0 -1.676363       NaN       NaN
1  0.560776       NaN       NaN
2  0.674205       NaN       NaN
3 -0.172477       NaN  0.759635
4  1.394465       NaN  1.430571
5 -0.154991 -0.303014 -1.451250
6  0.991851 -0.085244  0.632400

In [415]:
df.dropna(thresh=3) #thresh는 삭제된 후 지정한 숫자만큼의 값이 들어있는지 확인할 수 있다.
#thresh=3이면 3개의 열에 데이터가 멀쩡한 곳만 나오게 되니 5와 6 행 인덱스에 속한거만 나오는 것을 볼 수 있다.

0         1        2
5 -0.154991 -0.303014 -1.45125
6  0.991851 -0.085244  0.63240

In [416]:
df

0         1         2
0 -1.676363       NaN       NaN
1  0.560776       NaN       NaN
2  0.674205       NaN       NaN
3 -0.172477       NaN  0.759635
4  1.394465       NaN  1.430571
5 -0.154991 -0.303014 -1.451250
6  0.991851 -0.085244  0.632400

In [419]:
df.dropna(thresh=2, axis=0) #이번에는 NaN 1개는 허용해주는 것이다.
#행 기준으로 보기 때문에 0,1,2인덱스는 NaN 2개가 있어서 못나오고 나머지는 나온다.

0         1         2
3 -0.172477       NaN  0.759635
4  1.394465       NaN  1.430571
5 -0.154991 -0.303014 -1.451250
6  0.991851 -0.085244  0.632400

In [420]:
df

0         1         2
0 -1.676363       NaN       NaN
1  0.560776       NaN       NaN
2  0.674205       NaN       NaN
3 -0.172477       NaN  0.759635
4  1.394465       NaN  1.430571
5 -0.154991 -0.303014 -1.451250
6  0.991851 -0.085244  0.632400

In [421]:
df.dropna(thresh=5, axis=1) #thresh는 5개까지 되는 값이 나와야 되는데 axis=1은 열기준이므로 열인덱스 1은 NaN 5개, 2는 3개라
#thresh가 5개가 안된다. 그래서 0인덱스만 나옴

0
0 -1.676363
1  0.560776
2  0.674205
3 -0.172477
4  1.394465
5 -0.154991
6  0.991851

In [422]:
df.dropna(thresh=3, axis=1) #좀 더 여유로워져서 NaN이 5개나 돼서 정상적인 값이 2개뿐인 1인덱스는 누락됐지만 나머지는 잘 나옴

0         2
0 -1.676363       NaN
1  0.560776       NaN
2  0.674205       NaN
3 -0.172477  0.759635
4  1.394465  1.430571
5 -0.154991 -1.451250
6  0.991851  0.632400

누락된 값 채우기

In [423]:
df

0         1         2
0 -1.676363       NaN       NaN
1  0.560776       NaN       NaN
2  0.674205       NaN       NaN
3 -0.172477       NaN  0.759635
4  1.394465       NaN  1.430571
5 -0.154991 -0.303014 -1.451250
6  0.991851 -0.085244  0.632400

In [424]:
df.fillna(0) #모든 값을 0으로 채우는 방법

0         1         2
0 -1.676363  0.000000  0.000000
1  0.560776  0.000000  0.000000
2  0.674205  0.000000  0.000000
3 -0.172477  0.000000  0.759635
4  1.394465  0.000000  1.430571
5 -0.154991 -0.303014 -1.451250
6  0.991851 -0.085244  0.632400

In [425]:
df

0         1         2
0 -1.676363       NaN       NaN
1  0.560776       NaN       NaN
2  0.674205       NaN       NaN
3 -0.172477       NaN  0.759635
4  1.394465       NaN  1.430571
5 -0.154991 -0.303014 -1.451250
6  0.991851 -0.085244  0.632400

In [428]:
df.fillna({1:0.5, 2:-1}) #1인덱스는 0.5 처리, 2인덱스는 -1 처리하는 방법.
#3인덱스 -1을 넣어도 3인덱스가 없기 때문에 실제 데이터 출력시 반영이 되지는 않는다.

0         1         2
0 -1.676363  0.500000 -1.000000
1  0.560776  0.500000 -1.000000
2  0.674205  0.500000 -1.000000
3 -0.172477  0.500000  0.759635
4  1.394465  0.500000  1.430571
5 -0.154991 -0.303014 -1.451250
6  0.991851 -0.085244  0.632400

In [429]:
df

0         1         2
0 -1.676363       NaN       NaN
1  0.560776       NaN       NaN
2  0.674205       NaN       NaN
3 -0.172477       NaN  0.759635
4  1.394465       NaN  1.430571
5 -0.154991 -0.303014 -1.451250
6  0.991851 -0.085244  0.632400

In [430]:
df.fillna({2:10}) #2인덱스에 10 넣기

0         1          2
0 -1.676363       NaN  10.000000
1  0.560776       NaN  10.000000
2  0.674205       NaN  10.000000
3 -0.172477       NaN   0.759635
4  1.394465       NaN   1.430571
5 -0.154991 -0.303014  -1.451250
6  0.991851 -0.085244   0.632400

In [431]:
df

0         1         2
0 -1.676363       NaN       NaN
1  0.560776       NaN       NaN
2  0.674205       NaN       NaN
3 -0.172477       NaN  0.759635
4  1.394465       NaN  1.430571
5 -0.154991 -0.303014 -1.451250
6  0.991851 -0.085244  0.632400

## 계층적 색인

1. pandas의 중요한 기능
- 축에 대해 다중(2개 이상) 색인 단계 지정 가능(MultiIndex)
- 고차원 데이터를 낮은 차원의 형식으로 다룰수 있게 해주는 기능

In [432]:
data = Series(np.random.randn(10), 
              index=[
                      ['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'd'], 
                      [1, 2, 3, 1, 2, 3, 1, 2, 2, 3]
              ])

In [433]:
data #눈이 아파보이지만 다중 색인을 지정할 수 있는 기능이다. a,b,c,d라는 집에 각각 숫자에 따른 방이 있는 셈이다.

a  1   -0.479796
   2   -1.657644
   3    0.711000
b  1    2.101854
   2    0.871879
   3    0.835836
c  1   -0.383271
   2   -2.435391
d  2   -0.304611
   3    1.072515
dtype: float64

In [436]:
type(data) 

pandas.core.series.Series

In [439]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 1, 2, 0, 1, 1, 2]])

In [440]:
data.values

array([-0.47979585, -1.65764382,  0.7110002 ,  2.10185387,  0.87187922,
        0.83583649, -0.3832712 , -2.43539146, -0.30461139,  1.07251478])

계층적으로 색인된 객체는 데이터의 부분 집합을 부분적 색인으로 접근이 가능

In [441]:
data['b']

1    2.101854
2    0.871879
3    0.835836
dtype: float64

In [442]:
data['b':'c'] 

b  1    2.101854
   2    0.871879
   3    0.835836
c  1   -0.383271
   2   -2.435391
dtype: float64

In [443]:
data.loc[['b', 'c']] #loc로 다중 지정시 대괄호 두개

b  1    2.101854
   2    0.871879
   3    0.835836
c  1   -0.383271
   2   -2.435391
dtype: float64

In [444]:
data

a  1   -0.479796
   2   -1.657644
   3    0.711000
b  1    2.101854
   2    0.871879
   3    0.835836
c  1   -0.383271
   2   -2.435391
d  2   -0.304611
   3    1.072515
dtype: float64

하위 계층의 객체 선택

In [445]:
data[:, 2] #모든 집에서 2에 속하는 방 부르기

a   -1.657644
b    0.871879
c   -2.435391
d   -0.304611
dtype: float64

계층적인 색인은 데이터를 재형성 가능

In [446]:
data.unstack()

1         2         3
a -0.479796 -1.657644  0.711000
b  2.101854  0.871879  0.835836
c -0.383271 -2.435391       NaN
d       NaN -0.304611  1.072515

In [447]:
data

a  1   -0.479796
   2   -1.657644
   3    0.711000
b  1    2.101854
   2    0.871879
   3    0.835836
c  1   -0.383271
   2   -2.435391
d  2   -0.304611
   3    1.072515
dtype: float64

In [448]:
data.unstack().stack()

a  1   -0.479796
   2   -1.657644
   3    0.711000
b  1    2.101854
   2    0.871879
   3    0.835836
c  1   -0.383271
   2   -2.435391
d  2   -0.304611
   3    1.072515
dtype: float64

In [450]:
frame = DataFrame(np.arange(12).reshape(4,3), 
                  index=[['a','a','b','b'], [1, 2, 1, 2]], 
                  columns=[['Ohio', 'Ohio', 'Colorado'], ['Green', 'Red', 'Green']])                                 

In [451]:
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [461]:
frame.index

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]],
           names=['key1', 'key2'])

In [462]:
frame.index.names

FrozenList(['key1', 'key2'])

In [463]:
frame.index.names = ['key1', 'key2']

In [464]:
frame.index.name

In [465]:
frame.index

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]],
           names=['key1', 'key2'])

In [466]:
frame.columns

MultiIndex(levels=[['Colorado', 'Ohio'], ['Green', 'Red']],
           labels=[[1, 1, 0], [0, 1, 0]],
           names=['state', 'color'])

In [467]:
frame.columns.names = ['state', 'color']

In [469]:
frame #상위행 이름 : key1(a,b), 하위행 이름 : key2(1,2 / 1,2)
#상위열 이름 : state(Ohio, Colorado), 하위행 이름 : ccolor(green, red / green)

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [470]:
frame['Ohio']

color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

계층 순서 바꾸고 정렬하기

In [471]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [472]:
frame.swaplevel('key1', 'key2') #key 1과 key2의 레벨을 전환한다. 

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [473]:
frame 

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [475]:
frame.sort_index(1)  #열 기준으로 오름차순 정렬릏 한다. 콜로라도 이름을 가진 것이 먼저 왼쪽으로 오게 된다.

state     Colorado  Ohio    
color        Green Green Red
key1 key2                   
a    1           2     0   1
     2           5     3   4
b    1           8     6   7
     2          11     9  10

단계별 요약통계
> level 옵션 : 한축에 대해 합을 구하고 싶은 단계 지정할 수 있는 옵션

In [478]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [481]:
frame.sum() #행을 기준으로 더해져서 0+3+6+9, 1+4+7+10...이 나옴

state     color
Ohio      Green    18
          Red      22
Colorado  Green    26
dtype: int64

In [483]:
frame.sum(level='key2') #key2 수준에서 행기준 덧셈. 각 행마다 (key 1 a+ key 1 b) (key 2 a + key 2 b) 로 이루어진다 보면 된다. 

state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16

DataFrame의 컬럼 사용하기

In [484]:
frame = DataFrame({'a':range(7), 'b':range(7, 0, -1), 
                   'c':['one', 'one', 'one', 'two', 'two', 'two', 'two'], 
                   'd' : [0, 1, 2, 0, 1, 2, 3]})

In [485]:
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [486]:
# 하나 이상의 칼럼을 색인으로 하는 새로운 DataFrame 생성
frame2 = frame.set_index(['c', 'd'])
frame2 #frame2는 c,d가 행으로 전환된다. 그러면서 가지고 있던 컬럼값이 상위 계층이 된다.

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [488]:
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [491]:
# 명시적으로 컬럼 남겨두기
frame.set_index(['c', 'd'], drop=False) #삭제 False를 통해 컬럼을 남길수도 있다.

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [492]:
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [493]:
#계층적 색인 단계를 칼럼으로 이동
frame2.reset_index() #인덱스를 리셋할 수도 있단다.

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1