# NumPy Basics

In [1]:
import numpy as np
#numpy 모듈을 np라는 이름을 지정해서 실행하겠다. np로 numpy 호출은 프로그래머간의 약속과도 같다.

## The NumPy ndarray: A Multidimensional Array Object

In [44]:
data = np.random.randn(3,4,2)
data 
#np.random은 난수를 발생시킨다. 여기서 randn은 지정하는 값에 따라 난수값이 들어갈 배열을 생성한다.

array([[[-1.07160038,  0.77213544],
        [ 0.67768273, -2.74904087],
        [-1.98877061,  0.28969734],
        [ 0.59604035, -1.10043352]],

       [[-0.21450774, -2.20882094],
        [-1.6517933 , -0.60640921],
        [-0.70369388, -1.18080112],
        [-1.95010782, -0.54874324]],

       [[ 1.02878709,  1.37843322],
        [-1.98032667, -0.69758901],
        [-0.81918616, -0.00904059],
        [-2.19148671,  2.08243582]]])

In [45]:
data * 10
data + data

array([[[-2.14320076,  1.54427087],
        [ 1.35536547, -5.49808173],
        [-3.97754122,  0.57939468],
        [ 1.19208071, -2.20086704]],

       [[-0.42901549, -4.41764188],
        [-3.3035866 , -1.21281843],
        [-1.40738776, -2.36160224],
        [-3.90021563, -1.09748648]],

       [[ 2.05757419,  2.75686643],
        [-3.96065335, -1.39517802],
        [-1.63837232, -0.01808117],
        [-4.38297343,  4.16487164]]])

In [47]:
data.shape #범위를 알 수 있게 해준다. 대괄호를 기준으로 가장 바깥쪽에 있는 대괄호의 갯수부터 작은 대괄호 안에 있는 값의 갯수까지.
#3x4x2는 가장 큰 3개의 차원이 있고 각 차원에는 4개의 작은 차원이 있고, 작은 차원 안에는 2개의 값이 존재한다.

(3, 4, 2)

In [50]:
data.dtype #자료형 타입, 안에 들어있는 값에 따라 유동적으로 변한다. 기본적으로 실수64 형을 유지한다.

dtype('float64')

### Creating ndarrays

In [51]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [52]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
arr2.ndim #차원 개수

2

In [18]:
arr2.shape #차원 크기

(2, 4)

In [53]:
arr1.dtype 

dtype('float64')

In [54]:
arr2.dtype #numpy의 특징으로 int값만 있다면 자동으로 int형으로 타입을 맞춰준다.

dtype('int32')

In [55]:
np.zeros(10) #0의 값만 들어있는 것을 1행 10열만큼 추가

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [56]:
np.zeros((3, 6)) #0의 값만 들어있는 것을 3행 6열만큼 추가

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
np.arange(15) #15라고 지정된 값 이전까지 증가값에 맞춰 생성하며 1씩 증가한다. 증가값은 지정할 수 있다.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
np.arange(17.5)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17.])

In [60]:
np.arange(0.2, 20) #0.2부터 시작하여 1씩 증가하여 20 전까지 증가

array([ 0.2,  1.2,  2.2,  3.2,  4.2,  5.2,  6.2,  7.2,  8.2,  9.2, 10.2,
       11.2, 12.2, 13.2, 14.2, 15.2, 16.2, 17.2, 18.2, 19.2])

In [61]:
np.arange(0, 20, 0.2) #0부터 시작하여 0.2씩 증가하여 20 전까지 증가

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8])

### Data Types for ndarrays

In [63]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)


In [64]:
arr1.dtype

dtype('float64')

In [65]:
arr2.dtype #dtype은 직접 본인이 배열을 생성할 때 정의해줄 수도 있다.

dtype('int32')

In [67]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [68]:
float_arr = arr.astype(np.float64)
float_arr.dtype #astype을 통해 타입을 변환할 수 있다.

dtype('float64')

In [69]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32) #float을 int형으로 변환할 시 소수점은 완전히 버려지게 된다.

array([ 3, -1, -2,  0, 12, 10])

In [73]:
int_array = np.arange(10)

In [74]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [76]:
int_array.astype(calibers.dtype) #정수형이었던 배열을 다른 실수형인 배열을 통해서도 변환할 수 있다.

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Arithmetic with NumPy Arrays

In [82]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [83]:
arr * arr
#[[1,2,3] * [[1,2,3] =  [[1*1, 2*2, 3*3]
#[4,5,6]]  [4,5,6]]    [4*4, 5*5, 6*6]]

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [84]:
arr - arr
#[[1,2,3] - [[1,2,3] =  [[1-1, 2-2, 3-3]
#[4,5,6]]  [4,5,6]]    [4-4, 5-5, 6-6]]

array([[0., 0., 0.],
       [0., 0., 0.]])

In [85]:
1 / arr

#[[1,1,1] - [[1,2,3] =  [[1/1, 1/2, 1/3]
#[1,1,1]]  [4,5,6]]    [1/4, 1/5, 1/6]]

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [86]:
arr ** 0.5

#[[1,2,3] ** [[0.5,0.5,0.5] =  [[1의 0.5제곱, 2의 0.5제곱, 3의 0.5제곱]
#[4,5,6]]    [0.5,0.5,0.5]]    [4의 0.5제곱, 5의 0.5제곱, 6의 0.5제곱]]

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [90]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [91]:
arr2 > arr
#[[0,4,1] > [[1,2,3] =  [[0<1, 4>2, 1<3]
#[7,2,12]]  [4,5,6]]    [7>4, 2<5, 12>6]]

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

In [98]:
arr = np.arange(10)
arr #arange를 활용해 0부터 10 이전까지의 값들을 증가값 1(기본)로 생성

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
arr[5] #인덱스 5(6번째 자리)에는 5가 있다.

5

In [100]:
arr[5:8] #인덱스 슬라이스 기능을 통해 5부터 8-1까지 생성가능하다.

array([5, 6, 7])

In [101]:
arr[5:8] = 12 #슬라이스로 추출한 인덱스에 값을 대입할 수 있다.

In [102]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [103]:
arr_slice = arr[5:8] #슬라이스로 추출한 인덱스를 다른 변수에 집어넣었다.
arr_slice

array([12, 12, 12])

In [105]:
arr_slice[1] = 12345 #슬라이스로 추출한 인덱스 1에 12345를 집어넣으면, 기존 arr에도 반영이 되어버린다.
arr #기존 추출한 곳은 인덱스 5부터 7까지였으므로 인덱스 6(7번째 자리)에 값이 바뀐 것을 확인할 수 있다.

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [106]:
arr_slice[:] = 64 #위와 같으나 따로 시작값과 끝값을 지정하지 않고 대입하면 모든 값이 변경된다.
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [107]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2] #arr2d의 인덱스2 즉 3번째 행을 가져온다.

array([7, 8, 9])

In [108]:
arr2d.shape #arr2d의 크기는 3x3이다. 3개의 차원 각각엔 3개의 값이 존재한다.

(3, 3)

In [109]:
arr2d.ndim #arr2d는 2차원이다.

2

In [112]:
arr2d[0][2] #=arr2d[0,2] 첫번째 행에 속하는 3번째 열의 값을 가져온다.

3

In [114]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d 

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [116]:
arr3d.ndim 

3

In [117]:
arr3d.shape

(2, 2, 3)

In [118]:
arr3d[0] #arr3d의 첫번째 차원을 가져온다. (2,2,3 중 맨 왼쪽) 2개의 차원이라 인덱스0과 인덱스1이 존재한다.

array([[1, 2, 3],
       [4, 5, 6]])

In [120]:
old_values = arr3d[0].copy()
arr3d[0] = 42

In [121]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [123]:
arr3d[0] = old_values
arr3d #이전에는 값을 대입하면 원본도 같이 바뀌었으나 copy 기능을 사용하면 원본에 영향을 끼치지않고 값이 복사된 다른 주소를 뽑아온다.

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [124]:
arr3d[1, 0]
#가장 큰 차원에 속하는 것 중 2번째 차원을 가져온다. 차원 안에는 또 2개의 차원이 있고 거기서 인덱스0에 해당하는 차원을 가져온다.

array([7, 8, 9])

In [126]:
x = arr3d[1]
x 

array([[ 7,  8,  9],
       [10, 11, 12]])

In [128]:
x.ndim #x는 arr3d의 첫번째 차원의 인덱스1에 속하는 차원만을 가져와서 2차원이다.

2

In [129]:
x.shape #2x3

(2, 3)

In [131]:
x[0] #인덱스 0에 속하는 차원

array([7, 8, 9])

#### Indexing with slices

In [132]:
arr
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [137]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [139]:
arr2d[:2]  #arr2d는 3x3의 차원이지만 끝자리를 인덱스2 즉 인덱스 0부터 1까지만 슬라이스해서 가져올 수 있다.

array([[1, 2, 3],
       [4, 5, 6]])

In [140]:
arr2d.ndim

2

In [136]:
arr2d.shape

(3, 3)

In [141]:
arr2d[:2, 1:] #arr2d의 가장 큰 차원은 0과 1을 가져오고, 그 중 열은 시작점을 인덱스 1부터 수행하였다. 

array([[2, 3],
       [5, 6]])

In [142]:
arr2d[1, :2] #arr2d의 인덱스1에 해당하는 차원만 인덱스 0~1까지 뽑아준다.

array([4, 5])

In [144]:
arr2d[:2, 2] #arr2d의 인덱스 0~1에 해당하는 차원 중 인덱스 2만 뽑아준다.

array([3, 6])

In [145]:
arr2d[:, :1] #arr2d의 모든 차원 중 인덱스 0만 뽑는다.

array([[1],
       [4],
       [7]])

In [147]:
arr2d[:2, 1:] = 0 #행 인덱스의 0,1 그리고 열의 인덱스 1,2는 0의 값을 가진다. 
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [176]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [177]:
data = np.random.randn(7, 4)

In [178]:
names #문자열 데이터가 표시된다.

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [179]:
data #2차원 지정된 난수모음

array([[-0.0160663 ,  1.46638063,  0.61349469,  2.04999499],
       [-1.48680662, -0.48375811, -0.75690428, -0.68132185],
       [ 0.20254473, -1.23655703, -2.03985234,  0.99580233],
       [-0.64153406,  0.68657885, -0.00328491,  0.80004059],
       [ 0.00341275, -1.26968825,  0.61048595,  1.76735964],
       [ 0.48600053,  0.43651071,  0.41095701,  0.79611498],
       [ 0.33650053, -1.24114173,  0.66729122, -0.58455562]])

In [155]:
names == 'Bob' #names 배열 중 이름이 'Bob'인지 검증

array([ True, False, False,  True, False, False, False])

In [157]:
data[names == 'Bob'] #검출된 true값을 다른 배열의 색인으로 활용하면, True 인덱스에 해당하는 값만 나오게 할 수 있다.

array([[ 0.38320043,  2.15682734,  0.42052956, -0.39182383],
       [-0.04278248,  0.09863306,  0.74266574, -1.38371533]])

In [159]:
data[names == 'Bob', 2:] #슬라이스와도 연계하여 사용할 수 있다.

array([[ 0.42052956, -0.39182383],
       [ 0.74266574, -1.38371533]])

In [161]:
data[names == 'Bob', 3]

array([-0.39182383, -1.38371533])

In [162]:
mask = (names == 'Bob') | (names == 'Will')
mask #mask에 이름이 'bob'이거나 'will'을 검증한다.

array([ True, False,  True,  True,  True, False, False])

In [163]:
data[mask] #역시 색인으로 활용할 수 있다.

array([[ 0.38320043,  2.15682734,  0.42052956, -0.39182383],
       [-0.93977648,  1.1940479 , -0.67733327,  0.06353342],
       [-0.04278248,  0.09863306,  0.74266574, -1.38371533],
       [ 0.84645651,  1.10400412,  0.18422832, -0.92944696]])

In [180]:
data[data < 0] = 0 #조건을 부여해서 값을 바꿀 수도 있다.
data

array([[0.        , 1.46638063, 0.61349469, 2.04999499],
       [0.        , 0.        , 0.        , 0.        ],
       [0.20254473, 0.        , 0.        , 0.99580233],
       [0.        , 0.68657885, 0.        , 0.80004059],
       [0.00341275, 0.        , 0.61048595, 1.76735964],
       [0.48600053, 0.43651071, 0.41095701, 0.79611498],
       [0.33650053, 0.        , 0.66729122, 0.        ]])

In [181]:
data = np.random.randn(7, 4)

In [182]:
data[names != 'Joe'] = 7 #다른 색인으로도 조건 부여를 통해 값을 바꿀 수 있다.
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.63939784, -0.66970169, -1.31321224,  0.30109005],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.42865589, -1.05281282, -2.26983235, -0.5105058 ],
       [-0.0115603 , -0.50574013,  1.30425697,  0.04774889]])

### Transposing Arrays and Swapping Axes

In [184]:
arr = np.arange(15).reshape((3, 5)) #0부터 15-1까지 배열을 모형 변형을 통해 바꿀 수 있다. 단, 기존값과 당연히 일치하게 맞춰야 한다.
arr #2차원 배열 3x5가 되었다. 4, 5로 바꿔버리면 arr는 15갠데 4x5=20이 되어 오류가 난다.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [189]:
arr.T #(3x5)에 해당하면 보통은 3줄 5칸이지만 이를 5줄 3칸으로 만들 수도 있다.
#차원 변형으로 인해 기존의 작은 차원이던 값들이 큰 차원 단위로 맞춰진다.

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [191]:
arr.T.ndim

2

In [192]:
arr.T.shape

(5, 3)

In [196]:
arr = np.random.randn(6, 3)
arr

array([[-0.57822196,  1.22158771,  1.03183185],
       [-0.43611815,  1.19089816,  1.06846567],
       [-1.40588694,  0.69518954, -0.55995598],
       [ 0.31417551, -1.89853481, -0.80348142],
       [-1.90538838,  0.44786069,  0.75641811],
       [ 1.13233702,  0.96219117,  0.28392764]])

In [197]:
np.dot(arr.T, arr) #수학인거 같다.... 아무튼 이런 식으로 arr.T와 arr을 계산할 수도 있다.

array([[ 7.512456  , -2.56337606, -1.647573  ],
       [-2.56337606,  8.12462894,  4.28103143],
       [-1.647573  ,  4.28103143,  3.8182122 ]])

In [201]:
arr = np.arange(16).reshape((2, 2, 4))
arr #3차원 배열

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [221]:
arr.transpose((2, 1, 0))

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [223]:
arr.transpose((1, 0, 2)) #T와 같은 역할을 해주지만, 다차원 배열부터는 행과 열뿐만 아니라 다른 차원이 겹치기 때문에, 축을 지정해서 바꾼다.
#아래의 경우에는 axis=2(인덱스 맞추기 기준)으로 하되, 차원을 한번 쪼개서 인덱스 0끼리, 인덱스1끼리 해당하는 것을 묶었다.

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [224]:
arr
arr.swapaxes(1, 2) #축번호를 받아 배열을 변환한다. 

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## Universal Functions: Fast Element-Wise Array Functions

In [251]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [228]:
#유니버셜 함수는 차원 안에 있는 데이터의 원소별 연산을 수행해준다. 
np.sqrt(arr) #arr의 제곱근을 구할 수 있다. 각 원소별로 구해진 것을 확인할 수 있다.

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [232]:
x = np.random.randn(8)
y = np.random.randn(8)
x


array([-0.79805996,  0.08224698, -0.71647212, -0.0936346 , -0.68538862,
       -0.16819128,  0.34075959,  0.36389127])

In [234]:
y

array([ 0.68412822, -1.03477663, -0.655876  ,  0.57554688,  0.11492368,
       -0.28060592,  1.36925863,  0.61198614])

In [235]:

np.maximum(x, y) #서로 다른 차원의 최대값을 구해준다

array([ 0.68412822,  0.08224698, -0.655876  ,  0.57554688,  0.11492368,
       -0.16819128,  1.36925863,  0.61198614])

In [243]:
arr = np.random.randn(7) * 5 #랜덤값을 생성하고 5를 곱한 모습
arr

array([-8.91740917, -4.67112943,  5.73066504, -2.51791929,  0.36649346,
       -9.86411169,  3.1462614 ])

In [244]:
remainder, whole_part = np.modf(arr) #각 원소의 '몫'과 '나머지'를 배열로 변환해준다.

In [245]:
remainder #나머지의 배열

array([-0.91740917, -0.67112943,  0.73066504, -0.51791929,  0.36649346,
       -0.86411169,  0.1462614 ])

In [246]:
whole_part #몫의 배열

array([-8., -4.,  5., -2.,  0., -9.,  3.])

In [247]:
arr #현재 arr의 값

array([-8.91740917, -4.67112943,  5.73066504, -2.51791929,  0.36649346,
       -9.86411169,  3.1462614 ])

In [252]:

np.sqrt(arr) #제곱근 계산

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [253]:
np.sqrt(arr, arr) #sqrt는 단항 유니버셜 함수로 이항 연산이 불가능하다.

TypeError: ufunc 'sqrt' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''

In [254]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Expressing Conditional Logic as Array Operations

In [255]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [257]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result #베열간 연산을 조건식으로 표현하고 싶을 때 리스트를 활용해 처리할 수 있다. 단, 이 방법은 책에 따르면 다차원배열에선 못쓴다.

[1.1, 2.2, 1.3, 1.4, 2.5]

In [258]:
result = np.where(cond, xarr, yarr)
result #numpy에서는 where라는 조건식을 활용할 수 있다. 조건, 참, 거짓으로 나뉘며 이에 따라 값이 출력되는 구조이다.

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [260]:
arr = np.random.randn(4, 4)
arr 

array([[ 0.11592707,  1.66239566, -2.28149142, -0.12031078],
       [ 1.76359287,  0.33925097, -0.78563793,  0.41862776],
       [ 0.13478945, -0.2779142 , -0.12205366,  0.22546885],
       [-1.58436506, -0.28402521, -0.3721591 ,  0.69716728]])

In [261]:
arr > 0 #arr 안의 배열이 0보다 큰지 체크. 0,1로 잘 나온다.

array([[ True,  True, False, False],
       [ True,  True, False,  True],
       [ True, False, False,  True],
       [False, False, False,  True]])

In [262]:
np.where(arr > 0, 2, -2) #이를 where절에 대입하면 아래와 같이 True면 2, False면 -2로 바꿀 수 있다.

array([[ 2,  2, -2, -2],
       [ 2,  2, -2,  2],
       [ 2, -2, -2,  2],
       [-2, -2, -2,  2]])

In [263]:
np.where(arr > 0, 2, arr) # set only positive values to 2 #오직 True에 해당하는 것만 2로 바꿀 수도 있다.

array([[ 2.        ,  2.        , -2.28149142, -0.12031078],
       [ 2.        ,  2.        , -0.78563793,  2.        ],
       [ 2.        , -0.2779142 , -0.12205366,  2.        ],
       [-1.58436506, -0.28402521, -0.3721591 ,  2.        ]])

### Mathematical and Statistical Methods

In [264]:
arr = np.random.randn(5, 4)
arr


array([[-0.77997881, -1.64952796,  1.45549129,  0.20710706],
       [ 1.59488053,  1.36859988,  0.84489767, -0.1974583 ],
       [-2.20861077,  0.10793884,  0.05635408, -0.0982947 ],
       [ 0.77507407,  0.69691611,  0.17191267,  1.90370638],
       [-1.47995141, -0.48227934, -0.16735988,  1.20895084]])

In [265]:
arr.mean() #배열 내 평균값을 구해준다.

0.16641841276634284

In [266]:
np.mean(arr) 

0.16641841276634284

In [268]:
arr.sum() #합

3.3283682553268568

In [269]:
np.sum(arr)

3.3283682553268568

In [270]:
arr.mean(axis=1) #→ 방향 기준으로 계산한다.

array([-0.19172711,  0.90272994, -0.53565314,  0.88690231, -0.23015995])

In [271]:
arr.sum(axis=0)#↓ 방향 기준으로 계산한다.

array([-2.09858639,  0.04164753,  2.36129583,  3.02401129])

In [272]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum() #각 원소 끼리 누적합을 구해준다.
#[0], [0+1], [0+1+2], [0+1+2+3], [0+1+2+3+4]...

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [273]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr #3x3의 2차원배열이다.

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [276]:
arr.cumsum(axis=0) #위에 적었듯 ↓기준으로 계산한다.
#[0]     ,  [1]      , [2]
#[0+3]   ,  [1+4]    , [2+5]
#[0+3+6] ,  [1+4+7]  , [2+5+8]

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [277]:
arr.cumprod(axis=1) #위에 적었듯 → 기준으로 계산한다. 참고로 누적곱셈이다.
#[0]  ,  [0*1]   , [0*2]
#[3]  ,  [3*4]   , [3*4*5]
#[6]  ,  [6*7]   , [6*7*8]

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

### Methods for Boolean Arrays

In [278]:
arr = np.random.randn(100)
(arr > 0).sum() # Number of positive values #100개의 랜덤한 값을 생성해 0보다 큰 놈은 True, 아닌 놈은 False로 처리한다.
#이 때 True의 합을 반환해준다.

45

In [279]:
bools = np.array([False, False, True, False])

In [280]:

bools.any() #논리합(OR)과 동일한 개념으로, 1과 0 중 뭐가 1(True)인지 검사한다.

True

In [281]:

bools.all() #논리곱(AND)과 동일한 개념으로, 모든 값이 1(True)인지 검사한다.

False

### Sorting

In [283]:
arr = np.random.randn(6)
arr

array([ 1.14273247, -0.34154704,  0.94511015, -0.6404297 ,  1.53569381,
       -0.48203169])

In [284]:

arr.sort() #원소값을 오름차순으로 정렬한다. 
arr 

array([-0.6404297 , -0.48203169, -0.34154704,  0.94511015,  1.14273247,
        1.53569381])

In [285]:
arr = np.random.randn(5, 3)
arr

array([[ 0.28715481,  0.55868305, -1.58434774],
       [ 2.36035538,  0.58779303,  1.74882943],
       [-0.92612944,  0.99908608,  1.44027406],
       [-0.06012015, -1.64692346,  0.87878378],
       [-0.95901543,  1.9834125 ,  0.90596672]])

In [286]:
arr.sort(1) #1차워 부분끼리만 값을 비교해서 오름차순으로 정렬한다.
arr

array([[-1.58434774,  0.28715481,  0.55868305],
       [ 0.58779303,  1.74882943,  2.36035538],
       [-0.92612944,  0.99908608,  1.44027406],
       [-1.64692346, -0.06012015,  0.87878378],
       [-0.95901543,  0.90596672,  1.9834125 ]])

In [287]:
large_arr = np.random.randn(1000)
large_arr.sort()

In [288]:
large_arr[int(0.05 * len(large_arr))] # 5% quantile
#분위수를 구하는 법. 배열을 정렬한 후 특정 분위의 값을 선택한다.

-1.6951658887864212

In [289]:
arr

array([[-1.58434774,  0.28715481,  0.55868305],
       [ 0.58779303,  1.74882943,  2.36035538],
       [-0.92612944,  0.99908608,  1.44027406],
       [-1.64692346, -0.06012015,  0.87878378],
       [-0.95901543,  0.90596672,  1.9834125 ]])